# **Experiment Notebook**



---
## 0. Setup Environment

### 0.a Install Environment and Mandatory Packages

In [ ]:
# Do not modify this code
!pip install -q utstd

from utstd.folders import *
from utstd.ipyrenders import *

at = AtFolder(
    course_code=36106,
    assignment="AT2",
)
at.run()

### 0.b Disable Warnings Messages

In [ ]:
# Do not modify this code
import warnings
warnings.simplefilter(action='ignore')

### 0.c Install Additional Packages

> If you are using additional packages, you need to install them here using the command: `! pip install <package_name>`

In [ ]:
# <Student to fill this section>

### 0.d Import Packages

In [1]:
# <Student to fill this section>
import pandas as pd
import altair as alt
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

/Users/ratikpant/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


---
## A. Project Description


In [ ]:
# <Student to fill this section>
student_name = "Ratik Pant"
student_id = "25116765"

In [ ]:
# Do not modify this code
print_tile(size="h1", key='student_name', value=student_name)

In [ ]:
# Do not modify this code
print_tile(size="h1", key='student_id', value=student_id)

In [ ]:
# <Student to fill this section>
business_objective = """
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='business_objective', value=business_objective)

---
## B. Experiment Description

In [ ]:
# Do not modify this code
experiment_id = "3"
print_tile(size="h1", key='experiment_id', value=experiment_id)

In [ ]:
# <Student to fill this section>
experiment_hypothesis = """
Present the hypothesis you want to test, the question you want to answer or the insight you are seeking.
Explain the reasons why you think it is worthwhile considering it
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='experiment_hypothesis', value=experiment_hypothesis)

In [ ]:
# <Student to fill this section>
experiment_expectations = """
Detail what will be the expected outcome of the experiment. If possible, estimate the goal you are expecting.
List the possible scenarios resulting from this experiment.
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='experiment_expectations', value=experiment_expectations)

---
## C. Data Understanding

In [2]:
# Do not modify this code
# Load training data
try:
    df_eng = pd.read_csv('/Users/ratikpant/Desktop/machinelearningass2/df_eng.csv')
except Exception as e:
    print(e)

In [4]:
df_eng.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 989 entries, 0 to 988
Data columns (total 29 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   scholarship                       989 non-null    int64  
 1   university_transport              989 non-null    int64  
 2   has_laptop                        989 non-null    int64  
 3   has_consulted_teacher             989 non-null    int64  
 4   co_curricular                     989 non-null    int64  
 5   health_issues                     989 non-null    int64  
 6   study_hours                       989 non-null    float64
 7   study_sessions                    989 non-null    float64
 8   on_probation                      989 non-null    int64  
 9   is_suspended                      989 non-null    int64  
 10  skills_development_hours          989 non-null    float64
 11  current_gpa                       989 non-null    float64
 12  performa

In [3]:
df_eng

scholarship  university_transport  has_laptop  has_consulted_teacher  \
0              1                     0           1                      1   
1              0                     0           1                      0   
2              1                     1           1                      1   
3              1                     0           1                      1   
4              1                     0           1                      1   
..           ...                   ...         ...                    ...   
984            0                     1           1                      0   
985            1                     1           1                      1   
986            0                     1           0                      0   
987            0                     1           1                      1   
988            0                     1           1                      0   

     co_curricular  health_issues  study_hours  study_sessions  on_probation  \
0                0              0          2.0             2.0             1   
1                0              1          3.5             2.0             0   
2                1              0          2.0             1.0             0   
3                0              0          1.0             2.0             0   
4                1              0          3.0             2.0             0   
..             ...            ...          ...             ...           ...   
984              1              0          1.0             2.0             1   
985              1              0          4.0             4.0             1   
986              1              0          3.0             3.0             1   
987              0              0          5.0             3.0             0   
988              1              0          3.0             2.0             0   

     is_suspended  ...  english_proficiency_Basic  \
0               0  ...                          1   
1               0  ...                          1   
2               0  ...                          1   
3               0  ...                          0   
4               0  ...                          0   
..            ...  ...                        ...   
984             0  ...                          1   
985             0  ...                          1   
986             0  ...                          1   
987             0  ...                          0   
988             0  ...                          0   

     english_proficiency_Intermediate living_arrangement_Bachelor  \
0                                   0                           1   
1                                   0                           1   
2                                   0                           0   
3                                   0                           0   
4                                   1                           1   
..                                ...                         ...   
984                                 0                           1   
985                                 0                           1   
986                                 0                           0   
987                                 1                           1   
988                                 1                           1   

     living_arrangement_Family  attendance_bin_Low  attendance_bin_Medium  \
0                            0                   0                      0   
1                            0                   0                      0   
2                            1                   0                      0   
3                            1                   0                      0   
4                            0                   0                      0   
..                         ...                 ...                    ...   
984                          0                   1                      0   
985                          0       

In [5]:
columns_to_remove = ['scholarship', 'university_transport', 'has_laptop', 'learning_mode_Offline', 
                     'learning_mode_Online', 'on_probation', 'is_suspended', 'income_bin_Low', 'income_bin_Medium',
                     'income_bin_High'
                    ]

In [6]:
df_eng.drop(columns = columns_to_remove, inplace = True)

In [9]:
df_eng.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 989 entries, 0 to 988
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   has_consulted_teacher             989 non-null    int64  
 1   co_curricular                     989 non-null    int64  
 2   health_issues                     989 non-null    int64  
 3   study_hours                       989 non-null    float64
 4   study_sessions                    989 non-null    float64
 5   skills_development_hours          989 non-null    float64
 6   current_gpa                       989 non-null    float64
 7   performance_group                 989 non-null    object 
 8   social_risk                       989 non-null    float64
 9   gpa_improvement                   989 non-null    float64
 10  study_time_per_Session            989 non-null    float64
 11  english_proficiency_Advance       989 non-null    int64  
 12  english_

In [20]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [21]:
#TARGET VARIABLE
y = df_eng.pop('performance_group')

In [22]:
#INDEPENDENT FEATURES
X = df_eng
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 989 entries, 0 to 988
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   has_consulted_teacher             989 non-null    int64  
 1   co_curricular                     989 non-null    int64  
 2   health_issues                     989 non-null    int64  
 3   study_hours                       989 non-null    float64
 4   study_sessions                    989 non-null    float64
 5   skills_development_hours          989 non-null    float64
 6   current_gpa                       989 non-null    float64
 7   social_risk                       989 non-null    float64
 8   gpa_improvement                   989 non-null    float64
 9   study_time_per_Session            989 non-null    float64
 10  english_proficiency_Advance       989 non-null    int64  
 11  english_proficiency_Basic         989 non-null    int64  
 12  english_

In [ ]:
#train test split before stratified k fold

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, stratify = y, random_state = 42)

In [24]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [26]:
for train_index, val_index in skf.split(X_train, y_train):
    X_train_fold, X_val_fold = X_train.iloc[train_index], X_train.iloc[val_index]
    y_train_fold, y_val_fold = y_train.iloc[train_index], y_train.iloc[val_index]

In [ ]:
#train set encoding

In [27]:
labelencoder = LabelEncoder()
y_train_fold = labelencoder.fit_transform(y_train_fold)

In [28]:
X_train = X_train_fold
X_train

has_consulted_teacher  co_curricular  health_issues  study_hours  \
101                      1              0              0          5.0   
330                      1              1              0          2.0   
730                      1              1              0          3.0   
58                       0              1              0          5.0   
403                      1              0              0          5.5   
..                     ...            ...            ...          ...   
546                      1              0              0          1.0   
340                      0              0              0          2.5   
504                      0              0              0          3.0   
639                      1              0              0          2.0   
882                      0              1              0          3.0   

     study_sessions  skills_development_hours  current_gpa  social_risk  \
101             3.5                       3.0     3.330000     0.200000   
330             2.0                       1.0     3.040612     0.500000   
730             3.0                       2.0     3.640000     1.000000   
58              2.0                       2.0     3.720000     1.000000   
403             2.0                       4.0     3.930000     0.272727   
..              ...                       ...          ...          ...   
546             2.0                       2.0     3.990000     7.000000   
340             1.5                       1.0     2.800000     0.800000   
504             2.0                       3.0     3.400000     1.000000   
639             1.0                       1.0     3.540000     1.000000   
882             2.0                       1.0     3.790000     1.666667   

     gpa_improvement  study_time_per_Session  english_proficiency_Advance  \
101        -0.350000                    1.43                            0   
330        -0.499388                    1.00                            0   
730         1.080000                    1.00                            0   
58         -0.130000                    2.50                            1   
403         0.000000                    2.75                            0   
..               ...                     ...                          ...   
546         1.100000                    0.50                            1   
340         0.500000                    1.67                            0   
504        -0.140000                    1.50                            0   
639         1.090000                    2.00                            1   
882         1.230000                    1.50                            1   

     english_proficiency_Basic  english_proficiency_Intermediate  \
101                          0                                 1   
330                          0                                 1   
730                          1                                 0   
58                           0                                 0   
403                          1                                 0   
..                         ...                               ...   
546                          0                                 0   
340                          0                                 1   
504                          0                                 1   
639                          0                                 0   
882                          0                                 0   

     living_arrangement_Bachelor  living_arrangement_Family  \
101                            0                          1   
330                            0                          1   
730                            0                          1   
58                             0                          1   
403                            1                          0   
..                           ...                        ...   
546                            1            

In [29]:
y_train = y_train_fold

In [ ]:
# val set 

In [30]:
labelencoder = LabelEncoder()
y_val_fold = labelencoder.fit_transform(y_val_fold)

In [31]:
X_val = X_val_fold
X_val

has_consulted_teacher  co_curricular  health_issues  study_hours  \
167                      0              0              1          2.0   
415                      0              0              0          7.0   
886                      0              0              1          1.0   
640                      0              1              1          3.0   
585                      0              1              0          2.0   
..                     ...            ...            ...          ...   
438                      1              0              0          2.0   
94                       1              0              0          4.5   
653                      0              1              0          2.0   
183                      0              0              0          4.0   
808                      0              1              0          2.0   

     study_sessions  skills_development_hours  current_gpa  social_risk  \
167             2.0                       0.0         3.10     3.500000   
415             3.5                       3.0         3.90     0.214286   
886             2.0                       2.0         3.80     2.000000   
640             1.0                       2.0         3.72     1.000000   
585             2.0                       2.0         3.61     1.500000   
..              ...                       ...          ...          ...   
438             1.0                       3.0         3.51     1.000000   
94              2.0                       1.0         3.23     0.888889   
653             1.0                       3.0         2.87     3.500000   
183             2.0                       1.0         2.84     0.500000   
808             2.0                       1.0         3.73     1.000000   

     gpa_improvement  study_time_per_Session  english_proficiency_Advance  \
167             0.16                    1.00                            0   
415             0.30                    2.00                            0   
886             1.04                    0.50                            0   
640             1.06                    3.00                            0   
585             1.07                    1.00                            0   
..               ...                     ...                          ...   
438             0.00                    2.00                            0   
94             -0.46                    2.25                            0   
653             1.11                    2.00                            0   
183            -0.09                    2.00                            0   
808             1.06                    1.00                            1   

     english_proficiency_Basic  english_proficiency_Intermediate  \
167                          1                                 0   
415                          0                                 1   
886                          0                                 1   
640                          0                                 1   
585                          0                                 1   
..                         ...                               ...   
438                          0                                 1   
94                           0                                 1   
653                          1                                 0   
183                          0                                 1   
808                          0                                 0   

     living_arrangement_Bachelor  living_arrangement_Family  \
167                            0                          1   
415                            1                          0   
886                            1                          0   
640                            0                          1   
585                            1                          0   
..                           ...                        ...   
438                            0            

In [32]:
y_val = y_val_fold

In [ ]:
#test set

In [33]:
labelencoder = LabelEncoder()
y_test = labelencoder.fit_transform(y_test)

In [34]:
#defining xtest
X_test

has_consulted_teacher  co_curricular  health_issues  study_hours  \
192                      1              0              0          3.0   
868                      0              0              1          3.0   
813                      0              1              0          3.0   
470                      1              1              1          2.0   
708                      0              0              0          2.0   
..                     ...            ...            ...          ...   
392                      0              0              0          3.0   
38                       1              0              0          1.5   
884                      0              1              0          3.0   
668                      1              0              0          3.0   
437                      1              1              0          1.0   

     study_sessions  skills_development_hours  current_gpa  social_risk  \
192             1.0                       2.0         3.74     1.333333   
868             1.0                       2.0         3.20     1.000000   
813             1.0                       2.0         3.84     1.000000   
470             1.0                       3.0         3.37     2.000000   
708             2.0                       2.0         3.80     1.000000   
..              ...                       ...          ...          ...   
392             2.0                       2.0         3.68     1.333333   
38              2.0                       6.0         2.76     2.000000   
884             3.0                       1.0         2.65     0.333333   
668             3.0                       1.0         3.55     0.666667   
437             1.0                       2.0         2.77     2.000000   

     gpa_improvement  study_time_per_Session  english_proficiency_Advance  \
192             0.10                    3.00                            0   
868             1.10                    3.00                            0   
813             1.08                    3.00                            0   
470            -0.29                    2.00                            1   
708             1.06                    1.00                            0   
..               ...                     ...                          ...   
392             0.00                    1.50                            0   
38             -0.25                    0.75                            0   
884             1.09                    1.00                            0   
668             1.09                    1.00                            0   
437             0.80                    1.00                            0   

     english_proficiency_Basic  english_proficiency_Intermediate  \
192                          0                                 1   
868                          0                                 1   
813                          0                                 1   
470                          0                                 0   
708                          0                                 1   
..                         ...                               ...   
392                          1                                 0   
38                           0                                 1   
884                          0                                 1   
668                          1                                 0   
437                          1                                 0   

     living_arrangement_Bachelor  living_arrangement_Family  \
192                            1                          0   
868                            1                          0   
813                            1                          0   
470                            0                          1   
708                            1                          0   
..                           ...                        ...   
392                            0            

---
## D. Feature Selection


In [10]:
# <Student to fill this section>

features_list = [ 'has_consulted_teacher',
    'co_curricular',
    'health_issues',
    'study_hours',
    'study_sessions',
    'skills_development_hours',
    'current_gpa',
    'performance_group',
    'social_risk',
    'gpa_improvement',
    'study_time_per_Session',
    'english_proficiency_Advance',
    'english_proficiency_Basic',
    'english_proficiency_Intermediate',
    'living_arrangement_Bachelor',
    'living_arrangement_Family',
    'attendance_bin_Low',
    'attendance_bin_Medium',
    'attendance_bin_High']

In [ ]:
# <Student to fill this section>
feature_selection_explanations = """
Provide a rationale on why you are selected these features but also why you decided to remove other ones
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='feature_selection_explanations', value=feature_selection_explanations)

---
## E. Data Preparation

### E.1 Data Transformation <put_name_here>


In [ ]:
# <Student to fill this section>

In [ ]:
# <Student to fill this section>
data_transformation_1_explanations = """
Provide some explanations on why you believe it is important to perform this data transformation and its impacts
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='data_transformation_1_explanations', value=data_transformation_1_explanations)

### E.2 Data Transformation <put_name_here>


In [ ]:
# <Student to fill this section>

In [ ]:
# <Student to fill this section>
data_transformation_2_explanations = """
Provide some explanations on why you believe it is important to perform this data transformation and its impacts
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='data_transformation_2_explanations', value=data_transformation_2_explanations)

### E.3 Data Transformation <put_name_here>


In [ ]:
# <Student to fill this section>

In [ ]:
# <Student to fill this section>
data_transformation_3_explanations = """
Provide some explanations on why you believe it is important to perform this data transformation and its impacts
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='data_transformation_3_explanations', value=data_transformation_3_explanations)

### G.n Fixing "\<describe_issue_here\>"

> You can add more cells related to data preparation in this section

---
## F. Feature Engineering

# It is performed in 0 experiment file

### F.1 New Feature "\<put_name_here\>"



In [ ]:
# <Student to fill this section>

In [ ]:
# <Student to fill this section>
feature_engineering_1_explanations = """
Provide some explanations on why you believe it is important to create this feature and its impacts
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='feature_engineering_1_explanations', value=feature_engineering_1_explanations)

### F.2 New Feature "\<put_name_here\>"


In [ ]:
# <Student to fill this section>

In [ ]:
# <Student to fill this section>
feature_engineering_2_explanations = """
Provide some explanations on why you believe it is important to create this feature and its impacts
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='feature_engineering_2_explanations', value=feature_engineering_2_explanations)

### F.3 New Feature "\<put_name_here\>"


In [ ]:
# <Student to fill this section>

In [ ]:
# <Student to fill this section>
feature_engineering_3_explanations = """
Provide some explanations on why you believe it is important to create this feature and its impacts
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='feature_engineering_3_explanations', value=feature_engineering_3_explanations)

### F.n Fixing "\<describe_issue_here\>"

> You can add more cells related to new features in this section

---
## G. Train Machine Learning Model

### G.1 Import Algorithm


In [ ]:
# <Student to fill this section>

In [40]:
from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

[CV] END colsample_bytree=1.0, gamma=0, learning_rate=0.1, max_depth=10, min_child_weight=5, n_estimators=20, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=1.0, gamma=0, learning_rate=0.1, max_depth=10, min_child_weight=5, n_estimators=20, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.01, max_depth=5, min_child_weight=1, n_estimators=70, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=1.0, gamma=0.2, learning_rate=0.01, max_depth=10, min_child_weight=5, n_estimators=70, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=0.8, gamma=0.4, learning_rate=0.05, max_depth=5, min_child_weight=3, n_estimators=40, subsample=0.6; total time=   0.0s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.05, max_depth=3, min_child_weight=5, n_estimators=40, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.2, max_depth=3, min_child_weight=3, n_estimators=40, subsample=0.8; tot

[CV] END colsample_bytree=1.0, gamma=0, learning_rate=0.1, max_depth=10, min_child_weight=5, n_estimators=20, subsample=0.8; total time=   0.1s
[CV] END colsample_bytree=0.8, gamma=0.4, learning_rate=0.01, max_depth=7, min_child_weight=3, n_estimators=40, subsample=1.0; total time=   0.0s
[CV] END colsample_bytree=1.0, gamma=0.2, learning_rate=0.01, max_depth=10, min_child_weight=5, n_estimators=70, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=0.8, gamma=0.4, learning_rate=0.05, max_depth=5, min_child_weight=3, n_estimators=40, subsample=0.6; total time=   0.0s
[CV] END colsample_bytree=0.6, gamma=0, learning_rate=0.05, max_depth=3, min_child_weight=5, n_estimators=40, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=0.8, gamma=0.1, learning_rate=0.1, max_depth=3, min_child_weight=3, n_estimators=70, subsample=0.6; total time=   0.0s
[CV] END colsample_bytree=0.8, gamma=0.1, learning_rate=0.1, max_depth=3, min_child_weight=3, n_estimators=70, subsample=0.6; to

[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.2, max_depth=10, min_child_weight=5, n_estimators=40, subsample=1.0; total time=   0.1s
[CV] END colsample_bytree=0.8, gamma=0.4, learning_rate=0.01, max_depth=7, min_child_weight=3, n_estimators=40, subsample=1.0; total time=   0.0s
[CV] END colsample_bytree=1.0, gamma=0.2, learning_rate=0.01, max_depth=10, min_child_weight=5, n_estimators=70, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=0.8, gamma=0.4, learning_rate=0.05, max_depth=5, min_child_weight=3, n_estimators=40, subsample=0.6; total time=   0.0s
[CV] END colsample_bytree=0.8, gamma=0.2, learning_rate=0.2, max_depth=3, min_child_weight=1, n_estimators=40, subsample=0.6; total time=   0.0s
[CV] END colsample_bytree=0.6, gamma=0.4, learning_rate=0.2, max_depth=7, min_child_weight=3, n_estimators=20, subsample=1.0; total time=   0.0s
[CV] END colsample_bytree=0.8, gamma=0.1, learning_rate=0.1, max_depth=3, min_child_weight=3, n_estimators=70, subsample=0.6;

[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.2, max_depth=10, min_child_weight=5, n_estimators=40, subsample=1.0; total time=   0.0s
[CV] END colsample_bytree=1.0, gamma=0, learning_rate=0.1, max_depth=10, min_child_weight=5, n_estimators=20, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=0.6, gamma=0.1, learning_rate=0.01, max_depth=5, min_child_weight=1, n_estimators=70, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=1.0, gamma=0.2, learning_rate=0.01, max_depth=10, min_child_weight=5, n_estimators=70, subsample=0.8; total time=   0.0s
[CV] END colsample_bytree=0.8, gamma=0.4, learning_rate=0.05, max_depth=5, min_child_weight=3, n_estimators=40, subsample=0.6; total time=   0.0s
[CV] END colsample_bytree=0.8, gamma=0.2, learning_rate=0.2, max_depth=3, min_child_weight=1, n_estimators=40, subsample=0.6; total time=   0.0s
[CV] END colsample_bytree=0.6, gamma=0.4, learning_rate=0.2, max_depth=7, min_child_weight=3, n_estimators=20, subsample=1.0; 

In [78]:
xgb_model = XGBClassifier(random_state=42)

# Define parameter grid
param_dist = {
    'n_estimators': [20, 40, 70],
    'max_depth': [3, 5,7],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'subsample': [0.6, 0.8, 1.0],
    'gamma': [0, 0.1, 0.2, 0.4],
    'min_child_weight': [1, 3]
}


In [79]:
# Randomized Search
random_search = RandomizedSearchCV(
    estimator=xgb_model,
    param_distributions=param_dist,
    n_iter=50,  # you can increase to 100 for better results
    scoring='recall_macro',  # because recall is important for you
    cv=5,
    verbose=2,
    random_state=42,
    n_jobs=-1
)

In [80]:
random_search.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits


/Users/ratikpant/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/Users/ratikpant/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/Users/ratikpant/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/Users/ratikpant/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/Users/ratikpant/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWar

RandomizedSearchCV(cv=5,
                   estimator=XGBClassifier(base_score=None, booster=None,
                                           callbacks=None,
                                           colsample_bylevel=None,
                                           colsample_bynode=None,
                                           colsample_bytree=None, device=None,
                                           early_stopping_rounds=None,
                                           enable_categorical=False,
                                           eval_metric=None, feature_types=None,
                                           gamma=None, grow_policy=None,
                                           importance_type=None,
                                           interaction_constraints=None,
                                           learning_rate...
                                           monotone_constraints=None,
                                           multi_strategy=None,
                                           n_estimators=None, n_jobs=None,
                                           num_parallel_tree=None,
                                           random_state=42, ...),
                   n_iter=50, n_jobs=-1,
                   param_distributions={'gamma': [0, 0.1, 0.2, 0.4],
                                        'learning_rate': [0.01, 0.05, 0.1, 0.2],
                                        'max_depth': [3, 5, 7],
                                        'min_child_weight': [1, 3],
                                        'n_estimators': [20, 40, 70],
                                        'subsample': [0.6, 0.8, 1.0]},
                   random_state=42, scoring='recall_macro', verbose=2)

In [81]:
print("Best Parameters: ", random_search.best_params_)

Best Parameters:  {'subsample': 0.8, 'n_estimators': 70, 'min_child_weight': 1, 'max_depth': 7, 'learning_rate': 0.05, 'gamma': 0.4}


#n_estimators: So the model can learn multiple small improvements step-by-step.

max_depth: To allow trees to grow deep enough to learn real patterns but not so deep that they overfit.

learning_rate: To slow down learning, so the model doesn’t jump to wrong conclusions.

min_child_weight: To ensure splits are meaningful, not based on noise.

subsample and colsample_bytree: To make trees a little different from each other (adds randomness), making ensemble stronger.

gamma: To avoid useless splits and make model simpler.

scale_pos_weight: If classes are imbalanced (say very few students fail), we adjust for that.

reg_alpha and reg_lambda: To keep the model simple and avoid overfitting on training data.

In [82]:
y_val_pred = random_search.predict(X_val)

In [83]:
print(confusion_matrix(y_val, y_val_pred))
print(classification_report(y_val, y_val_pred))

[[42  0  0  2]
 [ 0  9  0  0]
 [ 4  0 24  0]
 [ 2  0  1 74]]
              precision    recall  f1-score   support

           0       0.88      0.95      0.91        44
           1       1.00      1.00      1.00         9
           2       0.96      0.86      0.91        28
           3       0.97      0.96      0.97        77

    accuracy                           0.94       158
   macro avg       0.95      0.94      0.95       158
weighted avg       0.95      0.94      0.94       158



In [84]:
y_test_pred = random_search.predict(X_test)

In [86]:
print(confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

[[50  0  0  4]
 [ 0 11  0  0]
 [ 4  0 32  0]
 [ 3  0  0 94]]
              precision    recall  f1-score   support

           0       0.88      0.93      0.90        54
           1       1.00      1.00      1.00        11
           2       1.00      0.89      0.94        36
           3       0.96      0.97      0.96        97

    accuracy                           0.94       198
   macro avg       0.96      0.95      0.95       198
weighted avg       0.95      0.94      0.94       198



In [ ]:
# <Student to fill this section>
algorithm_selection_explanations = """
Provide some explanations on why you believe this algorithm is a good fit
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='algorithm_selection_explanations', value=algorithm_selection_explanations)

### G.2 Set Hyperparameters

In [ ]:
# <Student to fill this section>

In [ ]:
# <Student to fill this section>
hyperparameters_selection_explanations = """
Explain why you are tuning these hyperparameters
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='hyperparameters_selection_explanations', value=hyperparameters_selection_explanations)

### G.3 Fit Model

In [ ]:
# <Student to fill this section>

### G.4 Model Technical Performance

In [ ]:
# <Student to fill this section>

In [ ]:
# <Student to fill this section>
model_performance_explanations = """
Provide some explanations on model performance
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='model_performance_explanations', value=model_performance_explanations)

### G.5 Business Impact from Current Model Performance


In [ ]:
# <Student to fill this section>

In [ ]:
# <Student to fill this section>
business_impacts_explanations = """
Interpret the results of the experiments related to the business objective set earlier. Estimate the impacts of the incorrect results for the business (some results may have more impact compared to others)
"""

In [ ]:
# Do not modify this code
print_tile(size="h3", key='business_impacts_explanations', value=business_impacts_explanations)

## H. Experiment Outcomes

In [ ]:
# <Student to fill this section>
experiment_outcome = "" # Either 'Hypothesis Confirmed', 'Hypothesis Partially Confirmed' or 'Hypothesis Rejected'

In [ ]:
# Do not modify this code
print_tile(size="h2", key='experiment_outcomes_explanations', value=experiment_outcome)

In [ ]:
# <Student to fill this section>
experiment_results_explanations = """
Reflect on the outcome of the experiment and list the new insights you gained from it. Provide rationale for pursuing more experimentation with the current approach or call out if you think it is a dead end.
Given the results achieved and the overall objective of the project, list the potential next steps and experiments. For each of them assess the expected uplift or gains and rank them accordingly. If the experiment achieved the required outcome for the business, recommend the steps to deploy this solution into production.
"""

In [ ]:
# Do not modify this code
print_tile(size="h2", key='experiment_results_explanations', value=experiment_results_explanations)