# **Experiment Notebook**



---
## 0. Setup Environment

### 0.a Install Environment and Mandatory Packages

In [1]:
# Do not modify this code
!pip install -q utstd

from utstd.folders import *
from utstd.ipyrenders import *

at = AtFolder(
    course_code=36106,
    assignment="AT2",
)
at.run()

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 17.2 MB/s eta 0:00:00
Mounted at /content/gdrive

You can now save your data files in: /content/36106/assignment/AT2/data


### 0.b Disable Warnings Messages

In [3]:
# Do not modify this code
import warnings
warnings.simplefilter(action='ignore')

### 0.c Install Additional Packages

> If you are using additional packages, you need to install them here using the command: `! pip install <package_name>`

In [3]:
# <Student to fill this section>

### 0.d Import Packages

In [4]:
# <Student to fill this section>
import pandas as pd
import altair as alt
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


---
## A. Project Description


In [5]:
# <Student to fill this section>
student_name = ""
student_id = ""

In [6]:
# Do not modify this code
print_tile(size="h1", key='student_name', value=student_name)

In [7]:
# Do not modify this code
print_tile(size="h1", key='student_id', value=student_id)

In [5]:
# <Student to fill this section>
business_objective = """
The primary goal of this project is to develop a predictive model that accurately classifies university students into 4 performance categories—Excellent, Good, Average, Poor on their demographic, academic, behavioral, and socio-economic characteristics. This initiative is driven by the need to proactively identify students at risk of underperforming in the current academic semester and to ensure timely academic interventions.
"""

In [9]:
# Do not modify this code
print_tile(size="h3", key='business_objective', value=business_objective)

---
## B. Experiment Description

In [10]:
# Do not modify this code
experiment_id = "2"
print_tile(size="h1", key='experiment_id', value=experiment_id)

In [11]:
# <Student to fill this section>
experiment_hypothesis = """
Present the hypothesis you want to test, the question you want to answer or the insight you are seeking.
Explain the reasons why you think it is worthwhile considering it
"""

In [12]:
# Do not modify this code
print_tile(size="h3", key='experiment_hypothesis', value=experiment_hypothesis)

In [13]:
# <Student to fill this section>
experiment_expectations = """
Detail what will be the expected outcome of the experiment. If possible, estimate the goal you are expecting.
List the possible scenarios resulting from this experiment.
"""

In [14]:
# Do not modify this code
print_tile(size="h3", key='experiment_expectations', value=experiment_expectations)

---
## C. Data Understanding

In [13]:
# Do not modify this code
# Load training data
try:
    df_eng = pd.read_csv('/Users/ratikpant/Desktop/machinelearningass2/df_eng.csv')
except Exception as e:
    print(e)

In [18]:
df_eng.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 989 entries, 0 to 988
Data columns (total 29 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   scholarship                       989 non-null    int64  
 1   university_transport              989 non-null    int64  
 2   has_laptop                        989 non-null    int64  
 3   has_consulted_teacher             989 non-null    int64  
 4   co_curricular                     989 non-null    int64  
 5   health_issues                     989 non-null    int64  
 6   study_hours                       989 non-null    float64
 7   study_sessions                    989 non-null    float64
 8   on_probation                      989 non-null    int64  
 9   is_suspended                      989 non-null    int64  
 10  skills_development_hours          989 non-null    float64
 11  current_gpa                       989 non-null    float64
 12  performa

# refering from the previous experiment's feature selection and dropping columns that weren't helping the model enough. 

In [19]:
columns_to_remove = ['scholarship', 'university_transport', 'has_laptop', 'learning_mode_Offline', 'learning_mode_Online',
                    ]

In [22]:
df_eng.drop(columns = columns_to_remove, inplace = True)

In [25]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [26]:
#TARGET VARIABLE
y = df_eng.pop('performance_group')

In [27]:
#INDEPENDENT FEATURES
X = df_eng
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 989 entries, 0 to 988
Data columns (total 23 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   has_consulted_teacher             989 non-null    int64  
 1   co_curricular                     989 non-null    int64  
 2   health_issues                     989 non-null    int64  
 3   study_hours                       989 non-null    float64
 4   study_sessions                    989 non-null    float64
 5   on_probation                      989 non-null    int64  
 6   is_suspended                      989 non-null    int64  
 7   skills_development_hours          989 non-null    float64
 8   current_gpa                       989 non-null    float64
 9   social_risk                       989 non-null    float64
 10  gpa_improvement                   989 non-null    float64
 11  study_time_per_Session            989 non-null    float64
 12  english_

# run a  train test split and stratified k fold 

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, stratify = y, random_state = 42)

In [30]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [31]:
for train_index, val_index in skf.split(X_train, y_train):
    X_train_fold, X_val_fold = X_train.iloc[train_index], X_train.iloc[val_index]
    y_train_fold, y_val_fold = y_train.iloc[train_index], y_train.iloc[val_index]

# train set ; encoding the target variable

In [32]:
labelencoder = LabelEncoder()
y_train_fold = labelencoder.fit_transform(y_train_fold)

In [33]:
X_train = X_train_fold
X_train

has_consulted_teacher  co_curricular  health_issues  study_hours  \
101                      1              0              0          5.0   
330                      1              1              0          2.0   
730                      1              1              0          3.0   
58                       0              1              0          5.0   
403                      1              0              0          5.5   
..                     ...            ...            ...          ...   
546                      1              0              0          1.0   
340                      0              0              0          2.5   
504                      0              0              0          3.0   
639                      1              0              0          2.0   
882                      0              1              0          3.0   

     study_sessions  on_probation  is_suspended  skills_development_hours  \
101             3.5             0             0                       3.0   
330             2.0             0             0                       1.0   
730             3.0             0             0                       2.0   
58              2.0             0             0                       2.0   
403             2.0             0             0                       4.0   
..              ...           ...           ...                       ...   
546             2.0             0             0                       2.0   
340             1.5             1             0                       1.0   
504             2.0             0             0                       3.0   
639             1.0             0             0                       1.0   
882             2.0             0             0                       1.0   

     current_gpa  social_risk  ...  english_proficiency_Basic  \
101     3.330000     0.200000  ...                          0   
330     3.040612     0.500000  ...                          0   
730     3.640000     1.000000  ...                          1   
58      3.720000     1.000000  ...                          0   
403     3.930000     0.272727  ...                          1   
..           ...          ...  ...                        ...   
546     3.990000     7.000000  ...                          0   
340     2.800000     0.800000  ...                          0   
504     3.400000     1.000000  ...                          0   
639     3.540000     1.000000  ...                          0   
882     3.790000     1.666667  ...                          0   

     english_proficiency_Intermediate  living_arrangement_Bachelor  \
101                                 1                            0   
330                                 1                            0   
730                                 0                            0   
58                                  0                            0   
403                                 0                            1   
..                                ...                          ...   
546                                 0                            1   
340                                 1                            0   
504                                 1                            1   
639                                 0                            1   
882                                 0                            0   

     living_arrangement_Family  attendance_bin_Low  attendance_bin_Medium  \
101                          1                   0                      0   
330                          1                   0                      0   
730                          1                   0                      0   
58                           1                   0                      0   
403                          0                   0                      0   
..                         ...                 ...                    ...   
546                          0            

In [35]:
y_train = y_train_fold

# val set ; encoding the target variable

In [36]:
labelencoder = LabelEncoder()
y_val_fold = labelencoder.fit_transform(y_val_fold)

In [37]:
X_val = X_val_fold
X_val

has_consulted_teacher  co_curricular  health_issues  study_hours  \
167                      0              0              1          2.0   
415                      0              0              0          7.0   
886                      0              0              1          1.0   
640                      0              1              1          3.0   
585                      0              1              0          2.0   
..                     ...            ...            ...          ...   
438                      1              0              0          2.0   
94                       1              0              0          4.5   
653                      0              1              0          2.0   
183                      0              0              0          4.0   
808                      0              1              0          2.0   

     study_sessions  on_probation  is_suspended  skills_development_hours  \
167             2.0             0             0                       0.0   
415             3.5             0             0                       3.0   
886             2.0             0             0                       2.0   
640             1.0             1             0                       2.0   
585             2.0             0             0                       2.0   
..              ...           ...           ...                       ...   
438             1.0             0             0                       3.0   
94              2.0             0             0                       1.0   
653             1.0             0             0                       3.0   
183             2.0             1             0                       1.0   
808             2.0             1             0                       1.0   

     current_gpa  social_risk  ...  english_proficiency_Basic  \
167         3.10     3.500000  ...                          1   
415         3.90     0.214286  ...                          0   
886         3.80     2.000000  ...                          0   
640         3.72     1.000000  ...                          0   
585         3.61     1.500000  ...                          0   
..           ...          ...  ...                        ...   
438         3.51     1.000000  ...                          0   
94          3.23     0.888889  ...                          0   
653         2.87     3.500000  ...                          1   
183         2.84     0.500000  ...                          0   
808         3.73     1.000000  ...                          0   

     english_proficiency_Intermediate  living_arrangement_Bachelor  \
167                                 0                            0   
415                                 1                            1   
886                                 1                            1   
640                                 1                            0   
585                                 1                            1   
..                                ...                          ...   
438                                 1                            0   
94                                  1                            1   
653                                 0                            0   
183                                 1                            0   
808                                 0                            0   

     living_arrangement_Family  attendance_bin_Low  attendance_bin_Medium  \
167                          1                   0                      0   
415                          0                   0                      0   
886                          0                   0                      0   
640                          1                   0                      0   
585                          0                   0                      1   
..                         ...                 ...                    ...   
438                          1            

In [38]:
y_val = y_val_fold

# test set ; encoding the target variable

In [40]:
labelencoder = LabelEncoder()
y_test = labelencoder.fit_transform(y_test)

In [41]:
#defining xtest
X_test

has_consulted_teacher  co_curricular  health_issues  study_hours  \
192                      1              0              0          3.0   
868                      0              0              1          3.0   
813                      0              1              0          3.0   
470                      1              1              1          2.0   
708                      0              0              0          2.0   
..                     ...            ...            ...          ...   
392                      0              0              0          3.0   
38                       1              0              0          1.5   
884                      0              1              0          3.0   
668                      1              0              0          3.0   
437                      1              1              0          1.0   

     study_sessions  on_probation  is_suspended  skills_development_hours  \
192             1.0             0             0                       2.0   
868             1.0             0             0                       2.0   
813             1.0             1             0                       2.0   
470             1.0             0             0                       3.0   
708             2.0             1             0                       2.0   
..              ...           ...           ...                       ...   
392             2.0             0             0                       2.0   
38              2.0             0             0                       6.0   
884             3.0             0             0                       1.0   
668             3.0             0             0                       1.0   
437             1.0             0             0                       2.0   

     current_gpa  social_risk  ...  english_proficiency_Basic  \
192         3.74     1.333333  ...                          0   
868         3.20     1.000000  ...                          0   
813         3.84     1.000000  ...                          0   
470         3.37     2.000000  ...                          0   
708         3.80     1.000000  ...                          0   
..           ...          ...  ...                        ...   
392         3.68     1.333333  ...                          1   
38          2.76     2.000000  ...                          0   
884         2.65     0.333333  ...                          0   
668         3.55     0.666667  ...                          1   
437         2.77     2.000000  ...                          1   

     english_proficiency_Intermediate  living_arrangement_Bachelor  \
192                                 1                            1   
868                                 1                            1   
813                                 1                            1   
470                                 0                            0   
708                                 1                            1   
..                                ...                          ...   
392                                 0                            0   
38                                  1                            1   
884                                 1                            1   
668                                 0                            1   
437                                 0                            1   

     living_arrangement_Family  attendance_bin_Low  attendance_bin_Medium  \
192                          0                   0                      0   
868                          0                   1                      0   
813                          0                   0                      0   
470                          1                   0                      0   
708                          0                   1                      0   
..                         ...                 ...                    ...   
392                          1            

---
## D. Feature Selection


In [42]:
# <Student to fill this section>

features_list = [
    'has_consulted_teacher',
    'co_curricular',
    'health_issues',
    'study_hours',
    'study_sessions',
    'on_probation',
    'is_suspended',
    'skills_development_hours',
    'current_gpa',
    'social_risk',
    'gpa_improvement',
    'study_time_per_Session',
    'english_proficiency_Advance',
    'english_proficiency_Basic',
    'english_proficiency_Intermediate',
    'living_arrangement_Bachelor',
    'living_arrangement_Family',
    'attendance_bin_Low',
    'attendance_bin_Medium',
    'attendance_bin_High',
    'income_bin_Low',
    'income_bin_Medium',
    'income_bin_High'
]

In [17]:
# <Student to fill this section>
feature_selection_explanations = """
Provide a rationale on why you are selected these features but also why you decided to remove other ones
"""

In [18]:
# Do not modify this code
print_tile(size="h3", key='feature_selection_explanations', value=feature_selection_explanations)

---
## E. Data Preparation

### E.1 Data Transformation <put_name_here>


In [19]:
# <Student to fill this section>

In [20]:
# <Student to fill this section>
data_transformation_1_explanations = """
Provide some explanations on why you believe it is important to perform this data transformation and its impacts
"""

In [21]:
# Do not modify this code
print_tile(size="h3", key='data_transformation_1_explanations', value=data_transformation_1_explanations)

### E.2 Data Transformation <put_name_here>


In [22]:
# <Student to fill this section>

In [23]:
# <Student to fill this section>
data_transformation_2_explanations = """
Provide some explanations on why you believe it is important to perform this data transformation and its impacts
"""

In [24]:
# Do not modify this code
print_tile(size="h3", key='data_transformation_2_explanations', value=data_transformation_2_explanations)

### E.3 Data Transformation <put_name_here>


In [25]:
# <Student to fill this section>

In [26]:
# <Student to fill this section>
data_transformation_3_explanations = """
Provide some explanations on why you believe it is important to perform this data transformation and its impacts
"""

In [27]:
# Do not modify this code
print_tile(size="h3", key='data_transformation_3_explanations', value=data_transformation_3_explanations)

### G.n Fixing "\<describe_issue_here\>"

> You can add more cells related to data preparation in this section

---
## F. Feature Engineering

### F.1 New Feature "\<put_name_here\>"



In [28]:
# <Student to fill this section>

In [29]:
# <Student to fill this section>
feature_engineering_1_explanations = """
Provide some explanations on why you believe it is important to create this feature and its impacts
"""

In [30]:
# Do not modify this code
print_tile(size="h3", key='feature_engineering_1_explanations', value=feature_engineering_1_explanations)

### F.2 New Feature "\<put_name_here\>"


In [31]:
# <Student to fill this section>

In [32]:
# <Student to fill this section>
feature_engineering_2_explanations = """
Provide some explanations on why you believe it is important to create this feature and its impacts
"""

In [33]:
# Do not modify this code
print_tile(size="h3", key='feature_engineering_2_explanations', value=feature_engineering_2_explanations)

### F.3 New Feature "\<put_name_here\>"


In [34]:
# <Student to fill this section>

In [35]:
# <Student to fill this section>
feature_engineering_3_explanations = """
Provide some explanations on why you believe it is important to create this feature and its impacts
"""

In [36]:
# Do not modify this code
print_tile(size="h3", key='feature_engineering_3_explanations', value=feature_engineering_3_explanations)

### F.n Fixing "\<describe_issue_here\>"

> You can add more cells related to new features in this section

---
## G. Train Machine Learning Model

### G.1 Import Algorithm


In [37]:
# <Student to fill this section>

In [53]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix

In [44]:
rf = RandomForestClassifier(random_state = 42)

In [65]:
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [3, 5, 7],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['auto', 'sqrt', 'log2']
}

In [66]:
random_search = RandomizedSearchCV(estimator=rf, param_distributions=param_grid, n_iter=100, cv=5, verbose=2, random_state=42)
random_search.fit(X_train, y_train)

Fitting 5 folds for each of 100 candidates, totalling 500 fits
[CV] END max_depth=3, max_features=auto, min_samples_leaf=4, min_samples_split=10, n_estimators=50; total time=   0.0s
[CV] END max_depth=3, max_features=auto, min_samples_leaf=4, min_samples_split=10, n_estimators=50; total time=   0.0s
[CV] END max_depth=3, max_features=auto, min_samples_leaf=4, min_samples_split=10, n_estimators=50; total time=   0.0s
[CV] END max_depth=3, max_features=auto, min_samples_leaf=4, min_samples_split=10, n_estimators=50; total time=   0.0s
[CV] END max_depth=3, max_features=auto, min_samples_leaf=4, min_samples_split=10, n_estimators=50; total time=   0.0s
[CV] END max_depth=3, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estimators=50; total time=   0.0s
[CV] END max_depth=3, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estimators=50; total time=   0.0s
[CV] END max_depth=3, max_features=auto, min_samples_leaf=1, min_samples_split=10, n_estimators=50; tota

[CV] END max_depth=5, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=200; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=200; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=200; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=200; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_leaf=4, min_samples_split=10, n_estimators=200; total time=   0.1s
[CV] END max_depth=7, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END max_depth=7, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END max_depth=7, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END max_depth=7, max_features=log2, mi

[CV] END max_depth=5, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=1, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END max_depth=5, max_features=sqrt, min_sample

[CV] END max_depth=7, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=50; total time=   0.0s
[CV] END max_depth=3, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END max_depth=3, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END max_depth=3, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END max_depth=3, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END max_depth=3, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=100; total time=   0.0s
[CV] END max_depth=7, max_features=auto, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.0s
[CV] END max_depth=7, max_features=auto, min_samples_leaf=1, min_samples_split=5, n_estimators=200; total time=   0.0s
[CV] END max_depth=7, max_features=auto, min_sam

[CV] END max_depth=7, max_features=log2, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   0.1s
[CV] END max_depth=7, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.1s
[CV] END max_depth=7, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.1s
[CV] END max_depth=7, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.1s
[CV] END max_depth=7, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.1s
[CV] END max_depth=7, max_features=log2, min_samples_leaf=2, min_samples_split=5, n_estimators=200; total time=   0.1s
[CV] END max_depth=5, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=log2, min_samples_leaf=4, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=5, max_features=log2, min_sa

[CV] END max_depth=3, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END max_depth=3, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END max_depth=3, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END max_depth=3, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END max_depth=3, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=200; total time=   0.1s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END max_depth=5, max_features=sqrt, min_samples_leaf=2, min_samples_split=5, n_estimators=50; total time=   0.0s
[CV] END max_depth=5, max_features=sqrt, min_sample

[CV] END max_depth=3, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   0.1s
[CV] END max_depth=3, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   0.1s
[CV] END max_depth=3, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   0.1s
[CV] END max_depth=3, max_features=sqrt, min_samples_leaf=1, min_samples_split=10, n_estimators=200; total time=   0.1s
[CV] END max_depth=3, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=3, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=3, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=3, max_features=sqrt, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=   0.0s
[CV] END max_depth=3, max_features=sqrt, min

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42),
                   n_iter=100,
                   param_distributions={'max_depth': [3, 5, 7],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [50, 100, 200]},
                   random_state=42, verbose=2)

In [67]:
print("Best Parameters: ", random_search.best_params_)

Best Parameters:  {'n_estimators': 200, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 7}


In [68]:
y_val_pred = random_search.best_estimator_.predict(X_val)

In [69]:
print(confusion_matrix(y_val, y_val_pred))

print(classification_report(y_val, y_val_pred))


[[36  0  0  8]
 [ 1  0  8  0]
 [ 5  0 23  0]
 [ 5  0  1 71]]
              precision    recall  f1-score   support

           0       0.77      0.82      0.79        44
           1       0.00      0.00      0.00         9
           2       0.72      0.82      0.77        28
           3       0.90      0.92      0.91        77

    accuracy                           0.82       158
   macro avg       0.60      0.64      0.62       158
weighted avg       0.78      0.82      0.80       158



In [ ]:
#checking it on unseen test set

In [70]:
y_test_pred = random_search.best_estimator_.predict(X_test)

In [71]:
print(confusion_matrix(y_test, y_test_pred))

print(classification_report(y_test, y_test_pred))


[[47  0  0  7]
 [ 0  0 11  0]
 [ 4  0 31  1]
 [ 6  0  0 91]]
              precision    recall  f1-score   support

           0       0.82      0.87      0.85        54
           1       0.00      0.00      0.00        11
           2       0.74      0.86      0.79        36
           3       0.92      0.94      0.93        97

    accuracy                           0.85       198
   macro avg       0.62      0.67      0.64       198
weighted avg       0.81      0.85      0.83       198



In [38]:
# <Student to fill this section>
algorithm_selection_explanations = """
Provide some explanations on why you believe this algorithm is a good fit
"""

In [39]:
# Do not modify this code
print_tile(size="h3", key='algorithm_selection_explanations', value=algorithm_selection_explanations)

### G.2 Set Hyperparameters

In [40]:
# <Student to fill this section>

In [41]:
# <Student to fill this section>
hyperparameters_selection_explanations = """
I created a param_grid to automate hyperparameter tuning because manually adjusting parameters is slow, biased, and might miss better combinations.

I selected ranges based on common values that impact Random Forest performance the most (n_estimators, max_depth, splits, leaf size, features).
"""

In [42]:
# Do not modify this code
print_tile(size="h3", key='hyperparameters_selection_explanations', value=hyperparameters_selection_explanations)

# n_estimators = 300 → more trees to reduce variance and stabilize predictions.

# min_samples_split = 2 and min_samples_leaf = 1 → allow the trees to grow deeper and capture patterns better.

# max_features = log2 → smaller random feature subsets, increases model diversity, helps reduce overfitting.

# max_depth = None → trees can expand fully to capture complex patterns.

# In short, the model found the best trade-off between bias and variance using these settings automatically

### G.3 Fit Model

In [43]:
# <Student to fill this section>

### G.4 Model Technical Performance

In [44]:
# <Student to fill this section>

In [45]:
# <Student to fill this section>
model_performance_explanations = """
Accuracy: 89% — the model is correctly predicting 89% of the total cases.

Class 0 (Precision: 0.83, Recall: 0.89): Good at identifying true positives, slightly lower precision.

Class 1 (Precision: 1.00, Recall: 0.55): Very high precision but low recall — model misses many actual Class 1 cases.

Class 2 (Precision: 0.84, Recall: 0.89): Balanced and reliable predictions.

Class 3 (Precision: 0.94, Recall: 0.93): Very strong performance with both precision and recall.

Macro Average Recall: 81% — moderate ability across all classes, needs attention on minority classes.

Weighted Average Recall: 89% — good considering class imbalance.

Key Focus:

Recall is critical for the business — identifying as many true students at risk as possible.

Particularly need to improve recall for Class 1 where the model is underperforming.
"""

In [46]:
# Do not modify this code
print_tile(size="h3", key='model_performance_explanations', value=model_performance_explanations)

### G.5 Business Impact from Current Model Performance


In [47]:
# <Student to fill this section>

In [48]:
# <Student to fill this section>
business_impacts_explanations = """
Interpret the results of the experiments related to the business objective set earlier. Estimate the impacts of the incorrect results for the business (some results may have more impact compared to others)
"""

In [49]:
# Do not modify this code
print_tile(size="h3", key='business_impacts_explanations', value=business_impacts_explanations)

## H. Experiment Outcomes

In [50]:
# <Student to fill this section>
experiment_outcome = "" # Either 'Hypothesis Confirmed', 'Hypothesis Partially Confirmed' or 'Hypothesis Rejected'

In [51]:
# Do not modify this code
print_tile(size="h2", key='experiment_outcomes_explanations', value=experiment_outcome)

In [52]:
# <Student to fill this section>
experiment_results_explanations = """
Reflect on the outcome of the experiment and list the new insights you gained from it. Provide rationale for pursuing more experimentation with the current approach or call out if you think it is a dead end.
Given the results achieved and the overall objective of the project, list the potential next steps and experiments. For each of them assess the expected uplift or gains and rank them accordingly. If the experiment achieved the required outcome for the business, recommend the steps to deploy this solution into production.
"""

In [53]:
# Do not modify this code
print_tile(size="h2", key='experiment_results_explanations', value=experiment_results_explanations)