# **Experiment Notebook**



---
## 0. Setup Environment

### 0.a Install Environment and Mandatory Packages

In [1]:
# Do not modify this code
!pip install -q utstd

from utstd.folders import *
from utstd.ipyrenders import *

at = AtFolder(
    course_code=36106,
    assignment="AT2",
)
at.run()

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 13.7 MB/s eta 0:00:00
Mounted at /content/gdrive

You can now save your data files in: /content/36106/assignment/AT2/data


### 0.b Disable Warnings Messages

In [2]:
# Do not modify this code
import warnings
warnings.simplefilter(action='ignore')

### 0.c Install Additional Packages

> If you are using additional packages, you need to install them here using the command: `! pip install <package_name>`

In [3]:
# <Student to fill this section>

### 0.d Import Packages

In [3]:
# <Student to fill this section>
import pandas as pd
import altair as alt
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


---
## A. Project Description


In [5]:
# <Student to fill this section>
student_name = "Ratik Pant"
student_id = "25116765"

In [6]:
# Do not modify this code
print_tile(size="h1", key='student_name', value=student_name)

In [7]:
# Do not modify this code
print_tile(size="h1", key='student_id', value=student_id)

In [8]:
# <Student to fill this section>
business_objective = """
"""

In [9]:
# Do not modify this code
print_tile(size="h3", key='business_objective', value=business_objective)

---
## B. Experiment Description

In [10]:
# Do not modify this code
experiment_id = "4"
print_tile(size="h1", key='experiment_id', value=experiment_id)

In [11]:
# <Student to fill this section>
experiment_hypothesis = """
Present the hypothesis you want to test, the question you want to answer or the insight you are seeking.
Explain the reasons why you think it is worthwhile considering it
"""

In [12]:
# Do not modify this code
print_tile(size="h3", key='experiment_hypothesis', value=experiment_hypothesis)

In [13]:
# <Student to fill this section>
experiment_expectations = """
Detail what will be the expected outcome of the experiment. If possible, estimate the goal you are expecting.
List the possible scenarios resulting from this experiment.
"""

In [14]:
# Do not modify this code
print_tile(size="h3", key='experiment_expectations', value=experiment_expectations)

---
## C. Data Understanding

In [23]:
# Do not modify this code
# Load training data
try:
    df_eng = pd.read_csv('/Users/ratikpant/Desktop/machinelearningass2/df_eng.csv')
    
except Exception as e:
    print(e)

In [24]:
df_eng

scholarship  university_transport  has_laptop  has_consulted_teacher  \
0              1                     0           1                      1   
1              0                     0           1                      0   
2              1                     1           1                      1   
3              1                     0           1                      1   
4              1                     0           1                      1   
..           ...                   ...         ...                    ...   
984            0                     1           1                      0   
985            1                     1           1                      1   
986            0                     1           0                      0   
987            0                     1           1                      1   
988            0                     1           1                      0   

     co_curricular  health_issues  study_hours  study_sessions  on_probation  \
0                0              0          2.0             2.0             1   
1                0              1          3.5             2.0             0   
2                1              0          2.0             1.0             0   
3                0              0          1.0             2.0             0   
4                1              0          3.0             2.0             0   
..             ...            ...          ...             ...           ...   
984              1              0          1.0             2.0             1   
985              1              0          4.0             4.0             1   
986              1              0          3.0             3.0             1   
987              0              0          5.0             3.0             0   
988              1              0          3.0             2.0             0   

     is_suspended  ...  english_proficiency_Basic  \
0               0  ...                          1   
1               0  ...                          1   
2               0  ...                          1   
3               0  ...                          0   
4               0  ...                          0   
..            ...  ...                        ...   
984             0  ...                          1   
985             0  ...                          1   
986             0  ...                          1   
987             0  ...                          0   
988             0  ...                          0   

     english_proficiency_Intermediate living_arrangement_Bachelor  \
0                                   0                           1   
1                                   0                           1   
2                                   0                           0   
3                                   0                           0   
4                                   1                           1   
..                                ...                         ...   
984                                 0                           1   
985                                 0                           1   
986                                 0                           0   
987                                 1                           1   
988                                 1                           1   

     living_arrangement_Family  attendance_bin_Low  attendance_bin_Medium  \
0                            0                   0                      0   
1                            0                   0                      0   
2                            1                   0                      0   
3                            1                   0                      0   
4                            0                   0                      0   
..                         ...                 ...                    ...   
984                          0                   1                      0   
985                          0       

In [25]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [26]:
#TARGET VARIABLE
y = df_eng.pop('performance_group')

In [27]:
#INDEPENDENT FEATURES
X = df_eng
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 989 entries, 0 to 988
Data columns (total 28 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   scholarship                       989 non-null    int64  
 1   university_transport              989 non-null    int64  
 2   has_laptop                        989 non-null    int64  
 3   has_consulted_teacher             989 non-null    int64  
 4   co_curricular                     989 non-null    int64  
 5   health_issues                     989 non-null    int64  
 6   study_hours                       989 non-null    float64
 7   study_sessions                    989 non-null    float64
 8   on_probation                      989 non-null    int64  
 9   is_suspended                      989 non-null    int64  
 10  skills_development_hours          989 non-null    float64
 11  current_gpa                       989 non-null    float64
 12  social_r

In [ ]:
#train test split before stratified k fold

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, stratify = y, random_state = 42)

In [29]:
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [30]:
for train_index, val_index in skf.split(X_train, y_train):
    X_train_fold, X_val_fold = X_train.iloc[train_index], X_train.iloc[val_index]
    y_train_fold, y_val_fold = y_train.iloc[train_index], y_train.iloc[val_index]

In [ ]:
#train set encoding

In [31]:
labelencoder = LabelEncoder()
y_train_fold = labelencoder.fit_transform(y_train_fold)

In [32]:
X_train = X_train_fold
X_train

scholarship  university_transport  has_laptop  has_consulted_teacher  \
101            0                     0           1                      1   
330            1                     0           1                      1   
730            0                     0           1                      1   
58             1                     0           1                      0   
403            1                     0           1                      1   
..           ...                   ...         ...                    ...   
546            1                     0           1                      1   
340            0                     1           1                      0   
504            1                     0           1                      0   
639            0                     0           1                      1   
882            0                     1           1                      0   

     co_curricular  health_issues  study_hours  study_sessions  on_probation  \
101              0              0          5.0             3.5             0   
330              1              0          2.0             2.0             0   
730              1              0          3.0             3.0             0   
58               1              0          5.0             2.0             0   
403              0              0          5.5             2.0             0   
..             ...            ...          ...             ...           ...   
546              0              0          1.0             2.0             0   
340              0              0          2.5             1.5             1   
504              0              0          3.0             2.0             0   
639              0              0          2.0             1.0             0   
882              1              0          3.0             2.0             0   

     is_suspended  ...  english_proficiency_Basic  \
101             0  ...                          0   
330             0  ...                          0   
730             0  ...                          1   
58              0  ...                          0   
403             0  ...                          1   
..            ...  ...                        ...   
546             0  ...                          0   
340             0  ...                          0   
504             0  ...                          0   
639             0  ...                          0   
882             0  ...                          0   

     english_proficiency_Intermediate  living_arrangement_Bachelor  \
101                                 1                            0   
330                                 1                            0   
730                                 0                            0   
58                                  0                            0   
403                                 0                            1   
..                                ...                          ...   
546                                 0                            1   
340                                 1                            0   
504                                 1                            1   
639                                 0                            1   
882                                 0                            0   

     living_arrangement_Family  attendance_bin_Low  attendance_bin_Medium  \
101                          1                   0                      0   
330                          1                   0                      0   
730                          1                   0                      0   
58                           1                   0                      0   
403                          0                   0                      0   
..                         ...                 ...                    ...   
546                          0                   0                      0   
340                      

In [33]:
y_train = y_train_fold

In [34]:
# val set 

In [35]:
labelencoder = LabelEncoder()
y_val_fold = labelencoder.fit_transform(y_val_fold)

In [36]:
X_val = X_val_fold
X_val

scholarship  university_transport  has_laptop  has_consulted_teacher  \
167            1                     0           1                      0   
415            1                     0           1                      0   
886            0                     1           0                      0   
640            0                     0           1                      0   
585            0                     0           1                      0   
..           ...                   ...         ...                    ...   
438            1                     1           1                      1   
94             0                     0           1                      1   
653            0                     0           1                      0   
183            0                     1           1                      0   
808            0                     0           0                      0   

     co_curricular  health_issues  study_hours  study_sessions  on_probation  \
167              0              1          2.0             2.0             0   
415              0              0          7.0             3.5             0   
886              0              1          1.0             2.0             0   
640              1              1          3.0             1.0             1   
585              1              0          2.0             2.0             0   
..             ...            ...          ...             ...           ...   
438              0              0          2.0             1.0             0   
94               0              0          4.5             2.0             0   
653              1              0          2.0             1.0             0   
183              0              0          4.0             2.0             1   
808              1              0          2.0             2.0             1   

     is_suspended  ...  english_proficiency_Basic  \
167             0  ...                          1   
415             0  ...                          0   
886             0  ...                          0   
640             0  ...                          0   
585             0  ...                          0   
..            ...  ...                        ...   
438             0  ...                          0   
94              0  ...                          0   
653             0  ...                          1   
183             0  ...                          0   
808             0  ...                          0   

     english_proficiency_Intermediate  living_arrangement_Bachelor  \
167                                 0                            0   
415                                 1                            1   
886                                 1                            1   
640                                 1                            0   
585                                 1                            1   
..                                ...                          ...   
438                                 1                            0   
94                                  1                            1   
653                                 0                            0   
183                                 1                            0   
808                                 0                            0   

     living_arrangement_Family  attendance_bin_Low  attendance_bin_Medium  \
167                          1                   0                      0   
415                          0                   0                      0   
886                          0                   0                      0   
640                          1                   0                      0   
585                          0                   0                      1   
..                         ...                 ...                    ...   
438                          1                   0                      0   
94                       

In [37]:
y_val = y_val_fold

In [ ]:
#test set

In [38]:
labelencoder = LabelEncoder()
y_test = labelencoder.fit_transform(y_test)

In [39]:
#defining xtest
X_test

scholarship  university_transport  has_laptop  has_consulted_teacher  \
192            0                     0           1                      1   
868            0                     1           1                      0   
813            0                     0           1                      0   
470            0                     1           1                      1   
708            1                     0           1                      0   
..           ...                   ...         ...                    ...   
392            1                     1           1                      0   
38             0                     0           1                      1   
884            0                     1           1                      0   
668            0                     0           1                      1   
437            0                     1           1                      1   

     co_curricular  health_issues  study_hours  study_sessions  on_probation  \
192              0              0          3.0             1.0             0   
868              0              1          3.0             1.0             0   
813              1              0          3.0             1.0             1   
470              1              1          2.0             1.0             0   
708              0              0          2.0             2.0             1   
..             ...            ...          ...             ...           ...   
392              0              0          3.0             2.0             0   
38               0              0          1.5             2.0             0   
884              1              0          3.0             3.0             0   
668              0              0          3.0             3.0             0   
437              1              0          1.0             1.0             0   

     is_suspended  ...  english_proficiency_Basic  \
192             0  ...                          0   
868             0  ...                          0   
813             0  ...                          0   
470             0  ...                          0   
708             0  ...                          0   
..            ...  ...                        ...   
392             0  ...                          1   
38              0  ...                          0   
884             0  ...                          0   
668             0  ...                          1   
437             0  ...                          1   

     english_proficiency_Intermediate  living_arrangement_Bachelor  \
192                                 1                            1   
868                                 1                            1   
813                                 1                            1   
470                                 0                            0   
708                                 1                            1   
..                                ...                          ...   
392                                 0                            0   
38                                  1                            1   
884                                 1                            1   
668                                 0                            1   
437                                 0                            1   

     living_arrangement_Family  attendance_bin_Low  attendance_bin_Medium  \
192                          0                   0                      0   
868                          0                   1                      0   
813                          0                   0                      0   
470                          1                   0                      0   
708                          0                   1                      0   
..                         ...                 ...                    ...   
392                          1                   0                      0   
38                       

---
## D. Feature Selection


In [16]:
# <Student to fill this section>

features_list = []

In [17]:
# <Student to fill this section>
feature_selection_explanations = """
Provide a rationale on why you are selected these features but also why you decided to remove other ones
"""

In [18]:
# Do not modify this code
print_tile(size="h3", key='feature_selection_explanations', value=feature_selection_explanations)

---
## E. Data Preparation

### E.1 Data Transformation <put_name_here>


In [19]:
# <Student to fill this section>

In [20]:
# <Student to fill this section>
data_transformation_1_explanations = """
Provide some explanations on why you believe it is important to perform this data transformation and its impacts
"""

In [21]:
# Do not modify this code
print_tile(size="h3", key='data_transformation_1_explanations', value=data_transformation_1_explanations)

### E.2 Data Transformation <put_name_here>


In [22]:
# <Student to fill this section>

In [23]:
# <Student to fill this section>
data_transformation_2_explanations = """
Provide some explanations on why you believe it is important to perform this data transformation and its impacts
"""

In [24]:
# Do not modify this code
print_tile(size="h3", key='data_transformation_2_explanations', value=data_transformation_2_explanations)

### E.3 Data Transformation <put_name_here>


In [25]:
# <Student to fill this section>

In [26]:
# <Student to fill this section>
data_transformation_3_explanations = """
Provide some explanations on why you believe it is important to perform this data transformation and its impacts
"""

In [27]:
# Do not modify this code
print_tile(size="h3", key='data_transformation_3_explanations', value=data_transformation_3_explanations)

### G.n Fixing "\<describe_issue_here\>"

> You can add more cells related to data preparation in this section

---
## F. Feature Engineering

# feature engineering is done in 0 experiment file

### F.1 New Feature "\<put_name_here\>"



In [28]:
# <Student to fill this section>

In [29]:
# <Student to fill this section>
feature_engineering_1_explanations = """
Provide some explanations on why you believe it is important to create this feature and its impacts
"""

In [30]:
# Do not modify this code
print_tile(size="h3", key='feature_engineering_1_explanations', value=feature_engineering_1_explanations)

### F.2 New Feature "\<put_name_here\>"


In [31]:
# <Student to fill this section>

In [32]:
# <Student to fill this section>
feature_engineering_2_explanations = """
Provide some explanations on why you believe it is important to create this feature and its impacts
"""

In [33]:
# Do not modify this code
print_tile(size="h3", key='feature_engineering_2_explanations', value=feature_engineering_2_explanations)

### F.3 New Feature "\<put_name_here\>"


In [34]:
# <Student to fill this section>

In [35]:
# <Student to fill this section>
feature_engineering_3_explanations = """
Provide some explanations on why you believe it is important to create this feature and its impacts
"""

In [36]:
# Do not modify this code
print_tile(size="h3", key='feature_engineering_3_explanations', value=feature_engineering_3_explanations)

### F.n Fixing "\<describe_issue_here\>"

> You can add more cells related to new features in this section

---
## G. Train Machine Learning Model

### G.1 Import Algorithm


In [37]:
# <Student to fill this section>

In [47]:
from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

In [42]:
param_dist = {
    'C': np.logspace(-3, 3, 7),  
    'gamma': np.logspace(-3, 3, 7),  
    'kernel': ['linear', 'rbf', 'poly']  
}

In [43]:
svm = SVC()

In [44]:
random_search = RandomizedSearchCV(svm, param_distributions=param_dist, n_iter=50, cv=5, n_jobs=-1, random_state=42)

In [45]:
random_search.fit(X_train, y_train)

/Users/ratikpant/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/Users/ratikpant/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/Users/ratikpant/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/Users/ratikpant/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (
/Users/ratikpant/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWar

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=50, n_jobs=-1,
                   param_distributions={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03]),
                                        'gamma': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03]),
                                        'kernel': ['linear', 'rbf', 'poly']},
                   random_state=42)

In [46]:
print(f"Best parameters: {random_search.best_params_}")
print(f"Best cross-validation score: {random_search.best_score_}")

Best parameters: {'kernel': 'rbf', 'gamma': 0.001, 'C': 1000.0}
Best cross-validation score: 0.7881514810648669


In [48]:
y_val_pred  =random_search.predict(X_val)

In [50]:
print(confusion_matrix(y_val, y_val_pred))
print(classification_report(y_val, y_val_pred))

[[31  0  6  7]
 [ 0  5  4  0]
 [ 7  2 19  0]
 [ 9  0  2 66]]
              precision    recall  f1-score   support

           0       0.66      0.70      0.68        44
           1       0.71      0.56      0.62         9
           2       0.61      0.68      0.64        28
           3       0.90      0.86      0.88        77

    accuracy                           0.77       158
   macro avg       0.72      0.70      0.71       158
weighted avg       0.77      0.77      0.77       158



In [51]:
y_test_pred = random_search.predict(X_test)

In [52]:
print(confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred))

[[46  0  4  4]
 [ 0  6  5  0]
 [ 9  3 24  0]
 [11  0  2 84]]
              precision    recall  f1-score   support

           0       0.70      0.85      0.77        54
           1       0.67      0.55      0.60        11
           2       0.69      0.67      0.68        36
           3       0.95      0.87      0.91        97

    accuracy                           0.81       198
   macro avg       0.75      0.73      0.74       198
weighted avg       0.82      0.81      0.81       198



In [38]:
# <Student to fill this section>
algorithm_selection_explanations = """
Provide some explanations on why you believe this algorithm is a good fit
"""

In [39]:
# Do not modify this code
print_tile(size="h3", key='algorithm_selection_explanations', value=algorithm_selection_explanations)

### G.2 Set Hyperparameters

In [40]:
# <Student to fill this section>

In [41]:
# <Student to fill this section>
hyperparameters_selection_explanations = """
Explain why you are tuning these hyperparameters
"""

In [42]:
# Do not modify this code
print_tile(size="h3", key='hyperparameters_selection_explanations', value=hyperparameters_selection_explanations)

### G.3 Fit Model

In [43]:
# <Student to fill this section>

### G.4 Model Technical Performance

In [44]:
# <Student to fill this section>

In [53]:
# <Student to fill this section>
model_performance_explanations = """
Class 3 (Poor Performers):

The recall for class 3 is 0.87, which indicates that the model correctly identifies 87% of the actual poor performers. 
This is a strong result and aligns well with the business goal of identifying students who need support due to poor academic performance.
"""

In [46]:
# Do not modify this code
print_tile(size="h3", key='model_performance_explanations', value=model_performance_explanations)

### G.5 Business Impact from Current Model Performance


In [47]:
# <Student to fill this section>

In [54]:
# <Student to fill this section>
business_impacts_explanations = """
The Support Vector Machine (SVM) model has demonstrated solid performance, particularly in identifying poor performers (class 3), which aligns well with the business goal of targeting students who need intervention due to poor academic performance.
Model Performance Summary:
Class 3 (Poor Performers):
The recall for class 3 is 0.87, meaning the model correctly identifies 87% of the students who are performing poorly. This result is quite strong and reflects the model's ability to pinpoint those most in need of support, which is the primary business objective.
Class 0 (Average Performers):
The recall for class 0 is 0.85, meaning 85% of average performers are correctly identified. While this may not be the primary focus, it is important for the business to accurately recognize this group, as they represent a significant portion of the student body. This insight allows for additional resources or support to be applied where necessary to maintain overall academic performance.
"""

In [49]:
# Do not modify this code
print_tile(size="h3", key='business_impacts_explanations', value=business_impacts_explanations)

## H. Experiment Outcomes

In [50]:
# <Student to fill this section>
experiment_outcome = "" # Either 'Hypothesis Confirmed', 'Hypothesis Partially Confirmed' or 'Hypothesis Rejected'

In [51]:
# Do not modify this code
print_tile(size="h2", key='experiment_outcomes_explanations', value=experiment_outcome)

In [52]:
# <Student to fill this section>
experiment_results_explanations = """
Reflect on the outcome of the experiment and list the new insights you gained from it. Provide rationale for pursuing more experimentation with the current approach or call out if you think it is a dead end.
Given the results achieved and the overall objective of the project, list the potential next steps and experiments. For each of them assess the expected uplift or gains and rank them accordingly. If the experiment achieved the required outcome for the business, recommend the steps to deploy this solution into production.
"""

In [53]:
# Do not modify this code
print_tile(size="h2", key='experiment_results_explanations', value=experiment_results_explanations)

# end of experimentation